<?php

namespace Database\Seeders\Addresses;

use App\Models\Address\Country;
use Illuminate\Database\Seeder;

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $countries =[
            [
				'iso_code_2'           => 'AF',
				'iso_code_3'           => 'AFG',
				'iso_numeric'          => '4',
				'fips'                 => 'AF',
				'name'                 => ['en' => 'Afghanistan'],
                'full_name'            =>'Islamic Republic of Afghanistan',
				'capital'              => 'Kabul',
                'citizenship'          =>'Afghan',
				'area'                 => '647500',
				'population'           => '29121286',
				'continent_code'       => 'AS',
				'tld'                  => '.af',
                'currency'             =>'afghani',
				'currency_code'        => 'AFN',
                'currency_sub_unit'    =>'pul',
                'currency_symbol'      =>'\u060b',
				'calling_code'         => '93',
				'postal_code_format'   => '',
				'postal_code_regex'    => '',
				'languages'            => 'fa-AF,ps,uz-AF,tk',
				'neighbours'           => 'TM,CN,IR,TJ,PK,UZ',
				'equivalent_fips_code' => '',
				'flag'                 =>'AF.png',
				'region-code'          =>'142',
                'sub-region-code'      =>'034',
				'eea'                  =>false,
				'status'               => '1',


			],
            [
				'iso_code_2'           => 'AL',
				'iso_code_3'           => 'ALB',
				'iso_numeric'          => '8',
				'fips'                 => 'AL',
				'name'                 => ['en' => 'Albania'],
                'full_name'            =>'Republic of Albania',
				'capital'              => 'Tirana',
                'citizenship'          =>'Albanian',
				'area'                 => '28748',
				'population'           => '2986952',
				'continent_code'       => 'EU',
				'tld'                  => '.al',
                'currency'             =>'lek',
				'currency_code'        => 'ALL',
                'currency_sub_unit'    =>'(qindar (pl. qindarka))',
                'currency_symbol'      =>'Lek',
				'calling_code'         => '355',
				'postal_code_format'   => '',
				'postal_code_regex'    => '',
				'languages'            => 'sq,el',
				'neighbours'           => 'MK,GR,ME,RS,XK',
				'equivalent_fips_code' => '',
                'region-code'=>'150',
                'sub-region-code'=>'039',
                 'eea'=>false,
				'flag'     => 'AL.png',
			    'status'               => '1',


			],
            [
                'iso_code_2'           => 'AQ',
				'iso_code_3'           => '',
				'iso_numeric'          => '010',
				'fips'                 => 'AQ',
				'name'                 => ['en' => 'Albania'],
                'full_name'            =>'Antarctica',
				'capital'              => 'Antartica',
                'citizenship'          =>'of Antartica',
				'area'                 => '',
				'population'           => '',
				'continent_code'       => '',
				'tld'                  => '',
                'currency'             =>'',
				'currency_code'        => '',
                'currency_sub_unit'    =>'',
                'currency_symbol'      =>'',
				'calling_code'         => '672',
				'postal_code_format'   => '',
				'postal_code_regex'    => '',
				'languages'            => '',
				'neighbours'           => '',
				'equivalent_fips_code' => '',
                'region-code'          =>'',
                'sub-region-code'      =>'',
                 'eea'                 =>false,
				'flag'                 => 'AQ.png',
			    'status'               => '1',
            ],
            [
				'iso_code_2'                 => 'DZ',
				'iso_code_3'           => 'DZA',
				'iso_numeric'          => '12',
				'fips'                 => 'AG',
				'name'                 => ['en' => 'Algeria'],
                'full_name'            =>'People\u2019s Democratic Republic of Algeria',
				'capital'              => 'Algiers',
                'citizenship'          =>'Algerian',
				'area'                 => '2381740',
				'population'           => '34586184',
				'continent_code'       => 'AF',
				'tld'                  => '.dz',
                'currency'=>'Algerian dinar',
				'currency_code'        => 'DZD',
                'currency_sub_unit'=>'centime',
                'currency_symbol'=>'DZD',
				'calling_code'                => '213',
				'postal_code_format'   => '#####',
				'postal_code_regex'    => '^(d{5})$',
				'languages'            => 'ar-DZ,fr',
				'neighbours'           => 'NE,EH,LY,MR,TN,MA,ML',
				'equivalent_fips_code' => '',
                'region-code'=>'002',
                'sub-region-code'=>'015',
                'eea'=>false,
				'flag'     => 'DZ.png',
				'status'               => '1',


			],
            [
				'iso_code_2'                 => 'AS',
				'iso_code_3'                 => 'ASM',
				'iso_numeric'          => '16',
				'fips'                 => 'AQ',
				'name'                 => ['en' => 'American Samoa'],
                'full_name'=>'Territory of American',
				'capital'              => 'Pago Pago',
                'citizenship'=>'American Samoan',
				'area'                 => '199',
				'population'           => '57881',
				'continent_code'       => 'OC',
				'tld'                  => '.as',
                'currency'=>'US dollar',
				'currency_code'        => 'USD',
                'currency_sub_unit'=>'cent',
                'currency_symbol'=>'$',
				'calling_code'                => '+1-684',
				'postal_code_format'   => '',
				'postal_code_regex'    => '',
				'languages'            => 'en-AS,sm,to',
				'neighbours'           => '',
				'equivalent_fips_code' => '',
                'region-code'=>'009',
                'sub-region-code'=>'061',
                'eea'=>false,
				'flag'     => 'AS.png',
				'status'               => '1',


			],
            [
				'iso_code_2'                 => 'AD',
				'iso_code_3'           => 'AND',
				'iso_numeric'          => '20',
				'fips'                 => 'AN',
				'name'                 => ['en' => 'Andorra'],
                'full_name'=>'Principality of Andorra',
				'capital'              => 'Andorra la Vella',
                'citizenship'=>'Andorran',
				'area'                 => '468',
				'population'           => '84000',
				'continent_code'       => 'EU',
                'tld'                  => '.ad',
                'currency'=>'euro',
				'currency_code'        => 'EUR',
                'currency_sub_unit'=>'cent',
                'currency_symbol'=>'\u20ac',
				'calling_code'         => '376',
				'postal_code_format'   => 'AD###',
				'postal_code_regex'    => '^(?:AD)*(d{3})$',
				'languages'            => 'ca',
				'neighbours'           => 'ES,FR',
				'equivalent_fips_code' => '',
                'region-code'=>'150',
                'sub-region-code'=>'039',
                'eea'=>false,
				'flag'                 => 'AD.png',
				'status'               => '1',


			],
            [
				'iso_code_2'                 => 'AO',
				'iso_code_3'                 => 'AGO',
				'iso_numeric'          => '24',
				'fips'                 => 'AO',
				'name'                 => ['en' => 'Angola'],
                'full_name'=>'Republic of Angola',
				'capital'              => 'Luanda',
                'citizenship'=>'Angolan',
				'area'                 => '1246700',
				'population'           => '13068161',
				'continent_code'       => 'AF',
				'tld'                  => '.ao',
                'currency'=>'kwanza',
				'currency_code'        => 'AOA',
                'currency_sub_unit'=>'c\u00eantimo',
                'currency_symbol'=>'Kz',
				'calling_code'                => '244',
				'postal_code_format'   => '',
				'postal_code_regex'    => '',
				'languages'            => 'pt-AO',
				'neighbours'           => 'CD,NA,ZM,CG',
				'equivalent_fips_code' => '',
                'region-code'=>'002',
                'sub-region-code'=>'017',
                'eea'=>false,
				'flag'     => 'AO.png',
				'status'               => '1',


			],
            [
				'iso_code_2'                 => 'AG',
				'iso_code_3'                 => 'ATG',
				'iso_numeric'          => '28',
				'fips'                 => 'AC',
				'name'                 => ['en' => 'Antigua and Barbuda'],
                'full_name'=>'Antigua and Barbuda',
				'capital'              => 'St. John\'s',
                'citizenship'=>'of Antigua and Barbuda',
				'area'                 => '443',
				'population'           => '86754',
				'continent_code'       => 'NA',
				'tld'                  => '.ag',
                'currency'=>'East Caribbean dollar',
				'currency_code'        => 'XCD',
                'currency_sub_unit'=>'cent',
                'currency_symbol'=>'$',
				'calling_code'                => '+1-268',
				'postal_code_format'   => '',
				'postal_code_regex'    => '',
				'languages'            => 'en-AG',
				'neighbours'           => '',
				'equivalent_fips_code' => '',
                'region-code'=>'019',
                'sub-region-code'=>'029',
                'eea'=>false,
				'flag'     => 'AG.png',
				'status'               => '1',


			],
            [
				'iso_code_2'                 => 'AZ',
				'iso_code_3'                 => 'AZE',
				'iso_numeric'          => '31',
				'fips'                 => 'AJ',
				'name'                 => ['en' => 'Azerbaijan'],
                'full_name'=>'Republic of Azerbaijan',
				'capital'              => 'Baku',
                'citizenship'=>'Azerbaijani',
				'area'                 => '86600',
				'population'           => '8303512',
				'continent_code'       => 'AS',
				'tld'                  => '.az',
                'currency'=>'Azerbaijani manat',
                'currency_code'=>'AZN',
                'currency_sub_unit'=>'kepik (inv.)',
			    'currency_symbol'=>'\u043c\u0430\u043d',
				'calling_code'                => '994',
				'postal_code_format'   => 'AZ ####',
				'postal_code_regex'    => '^(?:AZ)*(d{4})$',
				'languages'            => 'az,ru,hy',
				'neighbours'           => 'GE,IR,AM,TR,RU',
				'equivalent_fips_code' => '',
                'region-code'=>'142',
                'sub-region-code'=>'145',
                'eea'=>false,
				'flag'     => 'AZ.png',
				'status'               => '1',


			],
            [
				'iso_code_2'                 => 'AR',
				'iso_code_3'                 => 'ARG',
				'iso_numeric'          => '32',
				'fips'                 => 'AR',
				'name'                 => ['en' => 'Argentina'],
                'full_name'=>'Argentine Republic',
				'capital'              => 'Buenos Aires',
                'citizenship'=>'Argentinian',
				'area'                 => '2766890',
				'population'           => '41343201',
				'continent_code'       => 'SA',
				'tld'                  => '.ar',
                'currency'=>'Argentine peso',
                'currency_code'=>'ARS',
                'currency_sub_unit'=>'centavo',
				'currency_symbol'=>'$',
				'calling_code'                => '54',
				'postal_code_format'   => '@####@@@',
				'postal_code_regex'    => '^([A-Z]d{4}[A-Z]{3})$',
				'languages'            => 'es-AR,en,it,de,fr,gn',
				'neighbours'           => 'CL,BO,UY,PY,BR',
				'equivalent_fips_code' => '',
                'region-code'=>'019',
                'sub-region-code'=>'005',
                'eea'=>false,
				'flag'     => 'AR.png',
				'status'               => '1',


			],
            [
				'iso_code_2'                 => 'AU',
				'iso_code_3'                 => 'AUS',
				'iso_numeric'          => '36',
				'fips'                 => 'AS',
				'name'                 => ['en' => 'Australia'],
                'full_name'=>'Commonwealth of Australia',
				'capital'              => 'Canberra',
                'citizenship'=>'Australian',
				'area'                 => '7686850',
				'population'           => '21515754',
				'continent_code'       => 'OC',
				'tld'                  => '.au',
                'currency'=>'Australian dollar',
                'currency_code'=>'AUD',
                'currency_sub_unit'=>'cent',
			    'currency_symbol'=>'$',
				'calling_code'                => '61',
				'postal_code_format'   => '####',
				'postal_code_regex'    => '^(d{4})$',
				'languages'            => 'en-AU',
				'neighbours'           => '',
				'equivalent_fips_code' => '',
                'region-code'=>'009',
                'sub-region-code'=>'053',
                'eea'=>false,
				'flag'=>'AU.png',
				'status'               => '1',


			],
            [
				'iso_code_2'                 => 'AT',
				'iso_code_3'                 => 'AUT',
				'iso_numeric'          => '40',
				'fips'                 => 'AU',
				'name'                 => ['en' => 'Austria'],
                'full_name'=>'Republic of Austria',
				'capital'              => 'Vienna',
                'citizenship'=>'Austrian',
				'area'                 => '83858',
				'population'           => '8205000',
				'continent_code'       => 'EU',
				'tld'                  => '.at',
                'currency'=>'euro',
                'currency_code'=>'EUR',
                'currency_sub_unit'=>'cent',
				'currency_symbol'=>'\u20ac',
				'calling_code'                => '43',
				'postal_code_format'   => '####',
				'postal_code_regex'    => '^(d{4})$',
				'languages'            => 'de-AT,hr,hu,sl',
				'neighbours'           => 'CH,DE,HU,SK,CZ,IT,SI,LI',
				'equivalent_fips_code' => '',
                'region-code'=>'150',
                'sub-region-code'=>'155',
                'eea'=>true,
				'flag'=>'AT.png',
				'status'               => '1',


			],
            [
				'iso_code_2'                 => 'BS',
				'iso_code_3'                 => 'BHS',
				'iso_numeric'          => '44',
				'fips'                 => 'BF',
				'name'                 => ['en' => 'Bahamas'],
                'full_name'=>'Commonwealth of the Bahamas',
				'capital'              => 'Nassau',
                'citizenship'=>'Bahamian',
				'area'                 => '13940',
				'population'           => '301790',
				'continent_code'       => 'NA',
				'tld'                  => '.bs',
                'currency'=>'Bahamian dollar',
                'currency_code'=>'BSD',
                'currency_sub_unit'=>'cent',
				'currency_symbol'=>'$',
				'calling_code'                => '+1-242',
				'postal_code_format'   => '',
				'postal_code_regex'    => '',
				'languages'            => 'en-BS',
				'neighbours'           => '',
				'equivalent_fips_code' => '',
                'region-code'=>'019',
                'sub-region-code'=>'029',
                'eea'=>false,
				'flag'=>'BS.png',
				'status'               => '1',


			],
            [
				'iso_code_2'                 => 'BH',
				'iso_code_3'                 => 'BHR',
				'iso_numeric'          => '48',
				'fips'                 => 'BA',
				'name'                 => ['en' => 'Bahrain'],
                'full_name'=>'Kingdom of Bahrain',
				'capital'              => 'Manama',
                'citizenship'=>'Bahraini',
				'area'                 => '665',
				'population'           => '738004',
				'continent_code'       => 'AS',
				'tld'                  => '.bh',
                'currency'=>'Bahraini dinar',
                'currency_code'=>'BHD',
                'currency_sub_unit'=>'fils (inv.)',
				'currency_symbol'=>'BHD',
				'calling_code'                => '973',
				'postal_code_format'   => '####|###',
				'postal_code_regex'    => '^(d{3}d?)$',
				'languages'            => 'ar-BH,en,fa,ur',
				'neighbours'           => '',
				'equivalent_fips_code' => '',
                'region-code'=>'142',
                'sub-region-code'=>'145',
                'eea'=>false,
				'flag'=>'BH.png',
				'status'               => '1',


			],
            [
				'iso_code_2'                 => 'BD',
				'iso_code_3'                 => 'BGD',
				'iso_numeric'          => '50',
				'fips'                 => 'BG',
				'name'                 => ['en' => 'Bangladesh'],
                'full_name'=>'People\u2019s Republic of Bangladesh',
				'capital'              => 'Dhaka',
                'citizenship'=>'Bangladeshi',
				'area'                 => '144000',
				'population'           => '156118464',
				'continent_code'       => 'AS',
				'tld'                  => '.bd',
                'currency'=>'taka (inv.)',
                'currency_code'=>'BDT',
                'currency_sub_unit'=>'poisha (inv.)',
				'currency_symbol'=>'BDT',
				'calling_code'                => '880',
				'postal_code_format'   => '####',
				'postal_code_regex'    => '^(d{4})$',
				'languages'            => 'bn-BD,en',
				'neighbours'           => 'MM,IN',
				'equivalent_fips_code' => '',
                'region-code'=>'142',
                'sub-region-code'=>'034',
                'eea'=>false,
				'flag'=>'BD.png',
				'status'               => '1',


			],
            [
				'iso_code_2'                 => 'AM',
				'iso_code_3'                 => 'ARM',
				'iso_numeric'          => '51',
				'fips'                 => 'AM',
				'name'                 => ['en' => 'Armenia'],
                'full_name'=>'Republic of Armenia',
				'capital'              => 'Yerevan',
                'citizenship'=>'Armenian',
				'area'                 => '29800',
				'population'           => '2968000',
				'continent_code'       => 'AS',
				'tld'                  => '.am',
                'currency'=>'dram (inv.)',
                'currency_code'=>'AMD',
                'currency_sub_unit'=>'luma',
			    'currency_symbol'=>'AMD',
				'calling_code'                => '374',
				'postal_code_format'   => '######',
				'postal_code_regex'    => '^(d{6})$',
				'languages'            => 'hy',
				'neighbours'           => 'GE,IR,AZ,TR',
				'equivalent_fips_code' => '',
                'region-code'=>'142',
                'sub-region-code'=>'145',
                'eea'=>false,
				'flag'     => 'AM.png',
				'status'               => '1',


			],
            [
				'iso_code_2'                 => 'BB',
				'iso_code_3'                 => 'BRB',
				'iso_numeric'          => '52',
				'fips'                 => 'BB',
				'name'                 => ['en' => 'Barbados'],
                'full_name'=>'Barbados',
				'capital'              => 'Bridgetown',
                'citizenship'=>'Barbadian',
				'area'                 => '431',
				'population'           => '285653',
				'continent_code'       => 'NA',
				'tld'                  => '.bb',
                'currency'=>'Barbados dollar',
                'currency_code'=>'BBD',
                'currency_sub_unit'=>'cent',
				'currency_symbol'=>'$',
				'calling_code'                => '+1-246',
				'postal_code_format'   => 'BB#####',
				'postal_code_regex'    => '^(?:BB)*(d{5})$',
				'languages'            => 'en-BB',
				'neighbours'           => '',
				'equivalent_fips_code' => '',
                'region-code'=>'019',
                'sub-region-code'=>'029',
                'eea'=>false,
				'flag'     => 'BB.png',
				'status'               => '1',


			],
            [
				'iso_code_2'                 => 'BE',
				'iso_code_3'                 => 'BEL',
				'iso_numeric'          => '56',
				'fips'                 => 'BE',
				'name'                 => ['en' => 'Belgium'],
                'full_name'=>'Kingdom of Belgium',
				'capital'              => 'Brussels',
                'citizenship'=>'Belgian',
				'area'                 => '30510',
				'population'           => '10403000',
				'continent_code'       => 'EU',
				'tld'                  => '.be',
                'currency'=>'euro',
                'currency_code'=>'EUR',
                'currency_sub_unit'=>'cent',
				'currency_symbol'=>'\u20ac',
				'calling_code'                => '32',
				'postal_code_format'   => '####',
				'postal_code_regex'    => '^(d{4})$',
				'languages'            => 'nl-BE,fr-BE,de-BE',
				'neighbours'           => 'DE,NL,LU,FR',
				'equivalent_fips_code' => '',
                'region-code'=>'150',
                'sub-region-code'=>'155',
                'eea'=>true,
				'flag'     => 'BE.png',
				'status'               => '1',


			],
            [
				'iso_code_2'                 => 'BM',
				'iso_code_3'                 => 'BMU',
				'iso_numeric'          => '60',
				'fips'                 => 'BD',
				'name'                 => ['en' => 'Bermuda'],
                'full_name'=>'Bermuda',
				'capital'              => 'Hamilton',
                'citizenship'=>'Bermudian',
				'area'                 => '53',
				'population'           => '65365',
				'continent_code'       => 'NA',
				'tld'                  => '.bm',
                'currency'=>'Bermuda dollar',
                'currency_code'=>'BMD',
                'currency_sub_unit'=>'cent',
				'currency_symbol'=>'$',
				'calling_code'                => '+1-441',
				'postal_code_format'   => '@@ ##',
				'postal_code_regex'    => '^([A-Z]{2}d{2})$',
				'languages'            => 'en-BM,pt',
				'neighbours'           => '',
				'equivalent_fips_code' => '',
                'region-code'=>'019',
                'sub-region-code'=>'021',
                'eea'=>false,
				'flag'     => 'BM.png',
				'status'               => '1',


			],
            [
				'iso_code_2'                 => 'BT',
				'iso_code_3'                 => 'BTN',
				'iso_numeric'          => '64',
				'fips'                 => 'BT',
				'name'                 => ['en' => 'Bhutan'],
                'full_name'=>'Kingdom of Bhutan',
				'capital'              => 'Thimphu',
                'citizenship'=>'Bhutanese',
				'area'                 => '47000',
				'population'           => '699847',
				'continent_code'       => 'AS',
				'tld'                  => '.bt',
                'currency'=>'ngultrum (inv.)',
                'currency_code'=>'BTN',
                'currency_sub_unit'=>'chhetrum (inv.)',
				'currency_symbol'=>'BTN',
				'calling_code'                => '975',
				'postal_code_format'   => '',
				'postal_code_regex'    => '',
				'languages'            => 'dz',
				'neighbours'           => 'CN,IN',
				'equivalent_fips_code' => '',
                'region-code'=>'142',
                'sub-region-code'=>'034',
                'eea'=>false,
				'flag'     => 'BT.png',


				'status'               => '1',


			],
            [
				'iso_code_2'                 => 'BO',
				'iso_code_3'                 => 'BOL',
				'iso_numeric'          => '68',
				'fips'                 => 'BL',
				'name'                 => ['en' => 'Bolivia'],
                'full_name'=>'Plurinational State of Bolivia',
				'capital'              => 'Sucre',
                'citizenship'=>'Bolivian',
				'area'                 => '1098580',
				'population'           => '9947418',
				'continent_code'       => 'SA',
				'tld'                  => '.bo',
                'currency'=>'boliviano',
                'currency_code'=>'BOB',
                'currency_sub_unit'=>'centavo',
			    'currency_symbol'=>'$b',
				'calling_code'                => '591',
				'postal_code_format'   => '',
				'postal_code_regex'    => '',
				'languages'            => 'es-BO,qu,ay',
				'neighbours'           => 'PE,CL,PY,BR,AR',
				'equivalent_fips_code' => '',
                'region-code'=>'019',
                'sub-region-code'=>'005',
                'eea'=>false,
				'flag'     => 'BO.png',


				'status'               => '1',


			],
            [
				'iso_code_2'                 => 'BA',
				'iso_code_3'                 => 'BIH',
				'iso_numeric'          => '70',
				'fips'                 => 'BK',
				'name'                 => ['en' => 'Bosnia and Herzegovina'],
                'full_name'=>'Bosnia and Herzegovina',
				'capital'              => 'Sarajevo',
                'citizenship'=>'of Bosnia and Herzegovina',
				'area'                 => '51129',
				'population'           => '4590000',
				'continent_code'       => 'EU',
				'tld'                  => '.ba',
                'currency'=>'convertible mark',
                'currency_code'=>'BAM',
                'currency_sub_unit'=>'fening',
				'currency_symbol'=>'KM',
				'calling_code'                => '387',
				'postal_code_format'   => '#####',
				'postal_code_regex'    => '^(d{5})$',
				'languages'            => 'bs,hr-BA,sr-BA',
				'neighbours'           => 'HR,ME,RS',
				'equivalent_fips_code' => '',
                'region-code'=>'150',
                'sub-region-code'=>'039',
                'eea'=>false,
				'flag'     => 'BA.png',


				'status'               => '1',


			],
            [
				'iso_code_2'                 => 'BW',
				'iso_code_3'                 => 'BWA',
				'iso_numeric'          => '72',
				'fips'                 => 'BC',
				'name'                 => ['en' => 'Botswana'],
                'full_name'=>'Republic of Botswana',
				'capital'              => 'Gaborone',
                'citizenship'=>'Botswanan',
				'area'                 => '600370',
				'population'           => '2029307',
				'continent_code'       => 'AF',
				'tld'                  => '.bw',
                'currency'=>'pula (inv.)',
                'currency_code'=>'BWP',
                'currency_sub_unit'=>'thebe (inv.)',
				'currency_symbol'=>'P',
				'calling_code'                => '267',
				'postal_code_format'   => '',
				'postal_code_regex'    => '',
				'languages'            => 'en-BW,tn-BW',
				'neighbours'           => 'ZW,ZA,NA',
				'equivalent_fips_code' => '',
                'region-code'=>'002',
                'sub-region-code'=>'018',
                'eea'=>false,
				'flag'     => 'BW.png',


				'status'               => '1',


			],
            [
				'iso_code_2'                 => 'BV',
				'iso_code_3'                 => 'BVT',
				'iso_numeric'          => '74',
				'fips'                 => 'BV',
				'name'                 => ['en' => 'Bouvet Island'],
                'full_name'=>'Bouvet Island',
				'capital'=>'Bouvet island',
                'citizenship'=>'of Bouvet island',
				'area'                 => '49',
				'population'           => '0',
				'continent_code'       => 'AN',
				'tld'                  => '.bv',
                'currency'=>'',
                'currency_sub_unit'=>'',
				'currency_code'        => 'NOK',
                'currency_symbol'=>'kr',
				'calling_code'                => '47',
				'postal_code_format'   => '',
				'postal_code_regex'    => '',
				'languages'            => '',
				'neighbours'           => '',
				'equivalent_fips_code' => '',
                'region-code'=>'',
                'sub-region-code'=>'',
                'eea'=>false,
				'flag'     => 'BV.png',


				'status'               => '0',


			],
            [
				'iso_code_2'                 => 'BR',
				'iso_code_3'                 => 'BRA',
				'iso_numeric'          => '76',
				'fips'                 => 'BR',
				'name'                 => ['en' => 'Brazil'],
                'full_name'=>'Federative Republic of Brazil',
				'capital'              => 'Brasilia',
				'area'                 => '8511965',
				'population'           => '201103330',
				'continent_code'       => 'SA',
				'tld'                  => '.br',
                'currency'=>'real (pl. reais)',
                'currency_code'=>'BRL',
                'currency_sub_unit'=>'centavo',
				'currency_symbol'=>'R$',
				'calling_code'                => '55',
				'postal_code_format'   => '#####-###',
				'postal_code_regex'    => '^(d{8})$',
				'languages'            => 'pt-BR,es,en,fr',
				'neighbours'           => 'SR,PE,BO,UY,GY,PY,GF,VE,CO,AR',
				'equivalent_fips_code' => '',
                'region-code'=>'019',
                'sub-region-code'=>'005',
                'eea'=>false,
				'flag'     => 'BR.png',
				'status'               => '1',


			],
            [
				'iso_code_2'                 => 'BZ',
				'iso_code_3'                 => 'BLZ',
				'iso_numeric'          => '84',
				'fips'                 => 'BH',
				'name'                 => ['en' => 'Belize'],
                'full_name'=>'Belize',
				'capital'              => 'Belmopan',
                'citizenship'=>'Belizean',
				'area'                 => '22966',
				'population'           => '314522',
				'continent_code'       => 'NA',
				'tld'                  => '.bz',
                'currency'=>'Belize dollar',
                'currency_code'=>'BZD',
                'currency_sub_unit'=>'cent',
				'currency_symbol'=>'BZ$',
				'calling_code'                => '501',
				'postal_code_format'   => '',
				'postal_code_regex'    => '',
				'languages'            => 'en-BZ,es',
				'neighbours'           => 'GT,MX',
				'equivalent_fips_code' => '',
                'region-code'=>'019',
                'sub-region-code'=>'013',
                'eea'=>false,
				'flag'     => 'BZ.png',
				'status'               => '1',


			],
            [
				'iso_code_2'                 => 'IO',
				'iso_code_3'                 => 'IOT',
				'iso_numeric'          => '86',
				'fips'                 => 'IO',
				'name'                 => ['en' => 'British Indian Ocean Territory'],
                'full_name'=>'British Indian Ocean Territory',
				'capital'              => 'Diego Garcia',
                'citizenship'=>'Changosian',
				'area'                 => '60',
				'population'           => '4000',
				'continent_code'       => 'AS',
				'tld'                  => '.io',
                'currency'=>'US dollar',
                'currency_code'=>'USD',
                'currency_sub_unit'=>'cent',
				'currency_symbol'=>'$',
				'calling_code'                => '246',
				'postal_code_format'   => '',
				'postal_code_regex'    => '',
				'languages'            => 'en-IO',
				'neighbours'           => '',
				'equivalent_fips_code' => '',
                'region-code'=>'',
                'sub-region-code'=>'',
                'eea'=>false,
				'flag'     => 'IO.png',
				'status'               => '1',


			],
            [
				'iso_code_2'                 => 'SB',
				'iso_code_3'                 => 'SLB',
				'iso_numeric'          => '90',
				'fips'                 => 'BP',
				'name'                 => ['en' => 'Solomon Islands'],
                'full_name'=>'Solomon Islands',
				'capital'              => 'Honiara',
                'citizenship'=>'Solomon Islander',
				'area'                 => '28450',
				'population'           => '559198',
				'continent_code'       => 'OC',
				'tld'                  => '.sb',
                'currency'=>'Solomon Islands dollar',
                'currency_code'=>'SBD',
                'currency_sub_unit'=>'cent',
				'currency_symbol'=>'$',
				'calling_code'                => '677',
				'postal_code_format'   => '',
				'postal_code_regex'    => '',
				'languages'            => 'en-SB,tpi',
				'neighbours'           => '',
				'equivalent_fips_code' => '',
                'region-code'=>'009',
                'sub-region-code'=>'054',
                'eea'=>false,
				'flag'     => 'SB.png',


				'status'               => '1',


			],
            [
				'iso_code_2'                 => 'VG',
				'iso_code_3'                 => 'VGB',
				'iso_numeric'          => '92',
				'fips'                 => 'VI',
				'name'                 => ['en' => 'British Virgin Islands'],
                'full_name'=>'British Virgin Islands',
				'capital'              => 'Road Town',
                'citizenship'=>'British Virgin Islander;',
				'area'                 => '153',
				'population'           => '21730',
				'continent_code'       => 'NA',
				'tld'                  => '.vg',
                'currency'=>'US dollar',
                'currency_code'=>'USD',
                'currency_sub_unit'=>'cent',
				'currency_code'        => 'USD',
				'calling_code'                => '+1-284',
				'postal_code_format'   => '',
				'postal_code_regex'    => '',
				'languages'            => 'en-VG',
				'neighbours'           => '',
				'equivalent_fips_code' => '',
                'region-code'=>'019',
               'sub-region-code'=>'029',
                'eea'=>false,
				'flag'     => 'VG.png',


				'status'               => '1',


			],
            [
				'iso_code_2'                 => 'BN',
				'iso_code_3'                 => 'BRN',
				'iso_numeric'          => '96',
				'fips'                 => 'BX',
				'name'                 => ['en' => 'Brunei'],
                'full_name'=>'Brunei Darussalam',
				'capital'              => 'Bandar Seri Begawan',
                'citizenship'=>'Bruneian',
				'area'                 => '5770',
				'population'           => '395027',
				'continent_code'       => 'AS',
				'tld'                  => '.bn',
                'currency'=>'Brunei dollar',
                'currency_code'=>'BND',
                'currency_sub_unit'=>'sen (inv.)',
				'currency_symbol'=>'$',
				'calling_code'                => '673',
				'postal_code_format'   => '@@####',
				'postal_code_regex'    => '^([A-Z]{2}d{4})$',
				'languages'            => 'ms-BN,en-BN',
				'neighbours'           => 'MY',
				'equivalent_fips_code' => '',
                'region-code'=>'142',
                'sub-region-code'=>'035',
                'eea'=>false,
				'flag'     => 'BN.png',
			    'status'               => '1',


			],
            [
				'iso_code_2'                 => 'BG',
				'iso_code_3'                 => 'BGR',
				'iso_numeric'          => '100',
				'fips'                 => 'BU',
				'name'                 => ['en' => 'Bulgaria'],
                'full_name'=>'Republic of Bulgaria',
				'capital'              => 'Sofia',
                'citizenship'=>'Bulgarian',
				'area'                 => '110910',
				'population'           => '7148785',
				'continent_code'       => 'EU',
				'tld'                  => '.bg',
                'currency'=>'lev (pl. leva)',
                'currency_code'=>'BGN',
                'currency_sub_unit'=>'stotinka',
				'currency_symbol'=>'\u043b\u0432',
				'calling_code'                => '359',
				'postal_code_format'   => '####',
				'postal_code_regex'    => '^(d{4})$',
				'languages'            => 'bg,tr-BG,rom',
				'neighbours'           => 'MK,GR,RO,TR,RS',
				'equivalent_fips_code' => '',
                'region-code'=>'150',
                'sub-region-code'=>'151',
                'eea'=>true,
				'flag'     => 'BG.png',


				'status'               => '1',


			],
            [
				'iso_code_2'                 => 'MM',
				'iso_code_3'                 => 'MMR',
				'iso_numeric'          => '104',
				'fips'                 => 'BM',
				'name'                 => ['en' => 'Myanmar'],
                'full_name'=>'Union of Myanmar\/',
				'capital'              => 'Nay Pyi Taw',
                'citizenship'=>'Burmese',
				'area'                 => '678500',
				'population'           => '53414374',
				'continent_code'       => 'AS',
				'tld'                  => '.mm',
                'currency'=>'kyat',
                'currency_code'=>'MMK',
                'currency_sub_unit'=>'pya',
				'currency_symbol'=>'K',
				'calling_code'                => '95',
				'postal_code_format'   => '#####',
				'postal_code_regex'    => '^(d{5})$',
				'languages'            => 'my',
				'neighbours'           => 'CN,LA,TH,BD,IN',
				'equivalent_fips_code' => '',
                'region-code'=>'142',
                'sub-region-code'=>'035',
                'eea'=>false,
				'flag'     => 'MM.png',
				'status'               => '1',


			],
            [
				'iso_code_2'                 => 'BI',
				'iso_code_3'                 => 'BDI',
				'iso_numeric'          => '108',
				'fips'                 => 'BY',
				'name'                 => ['en' => 'Burundi'],
                'full_name'=>'Republic of Burundi',
				'capital'              => 'Bujumbura',
                'citizenship'=>'Burundian',
				'area'                 => '27830',
				'population'           => '9863117',
				'continent_code'       => 'AF',
				'tld'                  => '.bi',
                'currency'=>'Burundi franc',
                'currency_code'=>'BIF',
                'currency_sub_unit'=>'centime',
				'currency_symbol'=>'BIF',
				'calling_code'                => '257',
				'postal_code_format'   => '',
				'postal_code_regex'    => '',
				'languages'            => 'fr-BI,rn',
				'neighbours'           => 'TZ,CD,RW',
				'equivalent_fips_code' => '',
                'region-code'=>'002',
                'sub-region-code'=>'014',
                'eea'=>false,
				'flag'     => 'BI.png',


				'status'               => '1',


			],
            [
				'iso_code_2'                 => 'BY',
				'iso_code_3'                 => 'BLR',
				'iso_numeric'          => '112',
				'fips'                 => 'BO',
				'name'                 => ['en' => 'Belarus'],
                'full_name'=>'Republic of Belarus',
				'capital'              => 'Minsk',
                'citizenship'=>'Belarusian',
				'area'                 => '207600',
				'population'           => '9685000',
				'continent_code'       => 'EU',
				'tld'                  => '.by',
                'currency'=>'Belarusian rouble',
                'currency_code'=>'BYR',
                'currency_sub_unit'=>'kopek',
				'currency_symbol'=>'p.',
				'calling_code'                => '375',
				'postal_code_format'   => '######',
				'postal_code_regex'    => '^(d{6})$',
				'languages'            => 'be,ru',
				'neighbours'           => 'PL,LT,UA,RU,LV',
				'equivalent_fips_code' => '',
                'region-code'=>'150',
                'sub-region-code'=>'151',
                'eea'=>false,
                'calling_code'=>'375',
				'flag'     => 'BY.png',


				'status'               => '1',


			],
            [
				'iso_code_2'                 => 'KH',
				'iso_code_3'                 => 'KHM',
				'iso_numeric'          => '116',
				'fips'                 => 'CB',
				'name'                 => ['en' => 'Cambodia'],
                'full_name'=>'Kingdom of Cambodia',
				'capital'              => 'Phnom Penh',
                'citizenship'=>'Cambodian',
				'area'                 => '181040',
				'population'           => '14453680',
				'continent_code'       => 'AS',
				'tld'                  => '.kh',
                'currency'=>'riel',
                'currency_code'=>'KHR',
                'currency_sub_unit'=>'sen (inv.)',
				'currency_symbol'=>'\u17db',
				'calling_code'                => '855',
				'postal_code_format'   => '#####',
				'postal_code_regex'    => '^(d{5})$',
				'languages'            => 'km,fr,en',
				'neighbours'           => 'LA,TH,VN',
				'equivalent_fips_code' => '',
                'region-code'=>'142',
                'sub-region-code'=>'035',
                'eea'=>false,
				'flag'     => 'KH.png',


				'status'               => '1',


			],
            [
				'iso_code_2'                 => 'CM',
				'iso_code_3'                 => 'CMR',
				'iso_numeric'          => '120',
				'fips'                 => 'CM',
				'name'                 => ['en' => 'Cameroon'],
                'full_name'=>'Republic of Cameroon',
				'capital'              => 'Yaounde',
                'citizenship'=>'Cameroonian',
				'area'                 => '475440',
				'population'           => '19294149',
				'continent_code'       => 'AF',
				'tld'                  => '.cm',
                'currency'=>'CFA franc (BEAC)',
                'currency_code'=>'XAF',
                'currency_sub_unit'=>'centime',
				'currency_symbol'=>'FCF',
				'calling_code'                => '237',
				'postal_code_format'   => '',
				'postal_code_regex'    => '',
				'languages'            => 'fr-CM,en-CM',
				'neighbours'           => 'TD,CF,GA,GQ,CG,NG',
				'equivalent_fips_code' => '',
                'region-code'=>'002',
                'sub-region-code'=>'017',
                'eea'=>false,
				'flag'     => 'CM.png',


				'status'               => '1',


			],
            [
				'iso_code_2'                 => 'CA',
				'iso_code_3'                 => 'CAN',
				'iso_numeric'          => '124',
				'fips'                 => 'CA',
				'name'                 => ['en' => 'Canada'],
                'full_name'=>'Canada',
				'capital'              => 'Ottawa',
                'citizenship'=>'Canadian',
				'area'                 => '9984670',
				'population'           => '33679000',
				'continent_code'       => 'NA',
				'tld'                  => '.ca',
                'currency'=>'Canadian dollar',
                'currency_code'=>'CAD',
                'currency_sub_unit'=>'cent',
				'currency_symbol'=>'$',
				'calling_code'                => '1',
				'postal_code_format'   => '@#@ #@#',
				'postal_code_regex'    => '^([ABCEGHJKLMNPRSTVXY]d[ABCEGHJKLMNPRSTVWXYZ]) ?(d[ABCEGHJKLMNPRSTVWXYZ]d)$ ',
				'languages'            => 'en-CA,fr-CA,iu',
				'neighbours'           => 'US',
				'equivalent_fips_code' => '',
				'flag'     => 'CA.png',


				'status'               => '1',


			],
            [
				'iso_code_2'                 => 'CV',
				'iso_code_3'                 => 'CPV',
				'iso_numeric'          => '132',
				'fips'                 => 'CV',
				'name'                 => ['en' => 'Cape Verde'],
                'full_name'=>'Republic of Cape Verde',
				'capital'              => 'Praia',
                'citizenship'=>'Cape Verdean',
				'area'                 => '4033',
				'population'           => '508659',
				'continent_code'       => 'AF',
				'tld'                  => '.cv',
                'currency'=>'Cape Verde escudo',
                'currency_code'=>'CVE',
                'currency_sub_unit'=>'centavo',
				'currency_symbol'=>'CVE',
				'calling_code'                => '238',
				'postal_code_format'   => '####',
				'postal_code_regex'    => '^(d{4})$',
				'languages'            => 'pt-CV',
				'neighbours'           => '',
				'equivalent_fips_code' => '',
                'region-code'=>'002',
                'sub-region-code'=>'011',
                'eea'=>false,
				'flag'     => 'CV.png',


				'status'               => '1',


			],
            [
				'iso_code_2'                 => 'KY',
				'iso_code_3'                 => 'CYM',
				'iso_numeric'          => '136',
				'fips'                 => 'CJ',
				'name'                 => ['en' => 'Cayman Islands'],
                'full_name'=>'Cayman Islands',
				'capital'              => 'George Town',
                'citizenship'=>'Caymanian',
				'area'                 => '262',
				'population'           => '44270',
				'continent_code'       => 'NA',
				'tld'                  => '.ky',
                'currency'=>'Cayman Islands dollar',
                'currency_code'=>'KYD',
                'currency_sub_unit'=>'cent',
				'currency_symbol'=>'$',
				'calling_code'                => '+1-345',
				'postal_code_format'   => '',
				'postal_code_regex'    => '',
				'languages'            => 'en-KY',
				'neighbours'           => '',
				'equivalent_fips_code' => '',
                'region-code'=>'019',
               'sub-region-code'=>'029',
               'eea'=>false,
				'flag'     => 'KY.png',


				'status'               => '1',


			],
            [
				'iso_code_2'                 => 'CF',
				'iso_code_3'                 => 'CAF',
				'iso_numeric'          => '140',
				'fips'                 => 'CT',
				'name'                 => ['en' => 'Central African Republic'],
                'full_name'=>'Central African Republic',
				'capital'              => 'Bangui',
                'citizenship'=>'Central African',
				'area'                 => '622984',
				'population'           => '4844927',
				'continent_code'       => 'AF',
				'tld'                  => '.cf',
                'currency'=>'CFA franc (BEAC)',
                'currency_code'=>'XAF',
                'currency_sub_unit'=>'centime',
			    'currency_symbol'=>'FCF',
				'calling_code'                => '236',
				'postal_code_format'   => '',
				'postal_code_regex'    => '',
				'languages'            => 'fr-CF,sg,ln,kg',
				'neighbours'           => 'TD,SD,CD,SS,CM,CG',
				'equivalent_fips_code' => '',
                 'region-code'=>'002',
                'sub-region-code'=>'017',
                 'eea'=>false,
				'flag'     => 'CF.png',

				'status'               => '1',


			],
            [
				'iso_code_2'                 => 'LK',
				'iso_code_3'                 => 'LKA',
				'iso_numeric'          => '144',
				'fips'                 => 'CE',
				'name'                 => ['en' => 'Sri Lanka'],
                'full_name'=>'Democratic Socialist Republic of Sri Lanka',
				'capital'              => 'Colombo',
                'citizenship'=>'Sri Lankan',
				'area'                 => '65610',
				'population'           => '21513990',
				'continent_code'       => 'AS',
				'tld'                  => '.lk',
                'currency'=>'Sri Lankan rupee',
                'currency_code'=>'LKR',
                'currency_sub_unit'=>'cent',
				'currency_symbol'=>'\u20a8',
				'calling_code'                => '94',
				'postal_code_format'   => '#####',
				'postal_code_regex'    => '^(d{5})$',
				'languages'            => 'si,ta,en',
				'neighbours'           => '',
				'equivalent_fips_code' => '',
                'region-code'=>'142',
                'sub-region-code'=>'034',
                'eea'=>false,
				'flag'     => 'LK.png',


				'status'               => '1',


			],
            [
				'iso_code_2'                 => 'TD',
				'iso_code_3'                 => 'TCD',
				'iso_numeric'          => '148',
				'fips'                 => 'CD',
				'name'                 => ['en' => 'Chad'],
                'full_name'=>'Republic of Chad',
				'capital'              => 'N\'Djamena',
                'citizenship'=>'Chadian',
				'area'                 => '1284000',
				'population'           => '10543464',
				'continent_code'       => 'AF',
				'tld'                  => '.td',
                'currency'=>'CFA franc (BEAC)',
                'currency_code'=>'XAF',
                'currency_sub_unit'=>'centime',
				'currency_symbol'=>'XAF',
				'calling_code'                => '235',
				'postal_code_format'   => '',
				'postal_code_regex'    => '',
				'languages'            => 'fr-TD,ar-TD,sre',
				'neighbours'           => 'NE,LY,CF,SD,CM,NG',
				'equivalent_fips_code' => '',
                'region-code'=>'002',
                'sub-region-code'=>'017',
                'eea'=>false,
				'flag'     => 'TD.png',


				'status'               => '1',


			],
            [
				'iso_code_2'                 => 'CL',
				'iso_code_3'                 => 'CHL',
				'iso_numeric'          => '152',
				'fips'                 => 'CI',
				'name'                 => ['en' => 'Chile'],
                'full_name'=>'Republic of Chile',
				'capital'              => 'Santiago',
                'citizenship'=>'Chilean',
				'area'                 => '756950',
				'population'           => '16746491',
				'continent_code'       => 'SA',
				'tld'                  => '.cl',
                'currency'=>'Chilean peso',
                'currency_code'=>'CLP',
                'currency_sub_unit'=>'centavo',
				'currency_symbol'=>'CLP',
				'calling_code'                => '56',
				'postal_code_format'   => '#######',
				'postal_code_regex'    => '^(d{7})$',
				'languages'            => 'es-CL',
				'neighbours'           => 'PE,BO,AR',
				'equivalent_fips_code' => '',
                'region-code'=>'019',
                'sub-region-code'=>'005',
                'eea'=>false,
				'flag'     => 'CL.png',


				'status'               => '1',


			],
            [
				'iso_code_2'                 => 'CN',
				'iso_code_3'                 => 'CHN',
				'iso_numeric'          => '156',
				'fips'                 => 'CH',
				'name'                 => ['en' => 'China'],
                'full_name'=>'People\u2019s Republic of China',
				'capital'              => 'Beijing',
                'citizenship'=>'Chinese',
				'area'                 => '9596960',
				'population'           => '1330044000',
				'continent_code'       => 'AS',
				'tld'                  => '.cn',
                'currency'=>'renminbi-yuan (inv.)',
                'currency_code'=>'CNY',
                'currency_sub_unit'=>'jiao (10)',
				'currency_symbol'=>'\u00a5',
				'calling_code'                => '86',
				'postal_code_format'   => '######',
				'postal_code_regex'    => '^(d{6})$',
				'languages'            => 'zh-CN,yue,wuu,dta,ug,za',
				'neighbours'           => 'LA,BT,TJ,KZ,MN,AF,NP,MM,KG,PK,KP,RU,VN,IN',
				'equivalent_fips_code' => '',
                'region-code'=>'142',
                'sub-region-code'=>'030',
                'eea'=>false,
				'flag'     => 'CN.png',


				'status'               => '1',


			],
            [
				'iso_code_2'                 => 'TW',
				'iso_code_3'                 => 'TWN',
				'iso_numeric'          => '158',
				'fips'                 => 'TW',
				'name'                 => ['en' => 'Taiwan'],
                'full_name'=>'Republic of China, Taiwan (TW1)',
				'capital'              => 'Taipei',
                'citizenship'=>'Taiwanese',
				'area'                 => '35980',
				'population'           => '22894384',
				'continent_code'       => 'AS',
				'tld'                  => '.tw',
                'currency'=>'new Taiwan dollar',
                'currency_code'=>'TWD',
                'currency_sub_unit'=>'fen (inv.)',
				'currency_symbol'=>'NT$',
				'calling_code'                => '886',
				'postal_code_format'   => '#####',
				'postal_code_regex'    => '^(d{5})$',
				'languages'            => 'zh-TW,zh,nan,hak',
				'neighbours'           => '',
				'equivalent_fips_code' => '',
                'region-code'=>'142',
                'sub-region-code'=>'030',
                'eea'=>false,
				'flag'     => 'TW.png',


				'status'               => '1',


			],
            [
				'iso_code_2'                 => 'CX',
				'iso_code_3'                 => 'CXR',
				'iso_numeric'          => '162',
				'fips'                 => 'KT',
				'name'                 => 'Christmas Island',
                'full_name'=>'Christmas Island Territory',
				'capital'              => 'Flying Fish Cove',
                'citizenship'=>'Christmas Islander',
				'area'                 => '135',
				'population'           => '1500',
				'continent_code'       => 'AS',
				'tld'                  => '.cx',
                'currency'=>'Australian dollar',
                'currency_code'=>'AUD',
                'currency_sub_unit'=>'cent',
			    'currency_symbol'=>'$',
				'calling_code'                => '61',
				'postal_code_format'   => '####',
				'postal_code_regex'    => '^(d{4})$',
				'languages'            => 'en,zh,ms-CC',
				'neighbours'           => '',
				'equivalent_fips_code' => '',
                'region-code'=>'',
                'sub-region-code'=>'',
                'eea'=>false,
				'flag'     => 'CX.png',


				'status'               => '1',


			],
            [
				'iso_code_2'                 => 'CC',
				'iso_code_3'                 => 'CCK',
				'iso_numeric'          => '166',
				'fips'                 => 'CK',
				'name'                 => 'Cocos Islands',
                'full_name'=>'Territory of Cocos (Keeling) Islands',
				'capital'              => 'West Island',
                'citizenship'=>'Cocos Islander',
				'area'                 => '14',
				'population'           => '628',
				'continent_code'       => 'AS',
				'tld'                  => '.cc',
                'currency'=>'Australian dollar',
                'currency_code'=>'AUD',
                'currency_sub_unit'=>'cent',
				'currency_symbol'=>'$',
				'calling_code'                => '61',
				'postal_code_format'   => '',
				'postal_code_regex'    => '',
				'languages'            => 'ms-CC,en',
				'neighbours'           => '',
				'equivalent_fips_code' => '',
                'region-code'=>'',
                'sub-region-code'=>'',
                'eea'=>false,
				'flag'     => 'CC.png',


				'status'               => '1',


			],
            [
				'iso_code_2'           => 'CO',
				'iso_code_3'           => 'COL',
				'iso_numeric'          => '170',
				'fips'                 => 'CO',
				'name'                 => 'Colombia',
                'full_name'=>'Republic of Colombia',
				'capital'              => 'Bogota',
                'citizenship'=>'Colombian',
				'area'                 => '1138910',
				'population'           => '47790000',
				'continent_code'       => 'SA',
				'tld'                  => '.co',
                'currency'=>'Colombian peso',
                'currency_code'=>'COP',
                'currency_sub_unit'=>'centavo',
				'currency_symbol'=>'$',
				'calling_code'                => '57',
				'postal_code_format'   => '',
				'postal_code_regex'    => '',
				'languages'            => 'es-CO',
				'neighbours'           => 'EC,PE,PA,BR,VE',
				'equivalent_fips_code' => '',
                'region-code'=>'019',
                'sub-region-code'=>'005',
                'eea'=>false,
				'flag'     => 'CO.png',


				'status'               => '1',


			],
            [
				'iso_code_2'                 => 'KM',
				'iso_code_3'                 => 'COM',
				'iso_numeric'          => '174',
				'fips'                 => 'CN',
				'name'                 =>  'Comoros',
                'full_name'=>'Union of the Comoros',
				'capital'              => 'Moroni',
                'citizenship'=>'Comorian',
				'area'                 => '2170',
				'population'           => '773407',
				'continent_code'       => 'AF',
				'tld'                  => '.km',
                'currency'=>'Comorian franc',
                'currency_code'=>'KMF',
                'currency_sub_unit'=>'',
				'currency_symbol'=>'KMF',
				'calling_code'                => '269',
				'postal_code_format'   => '',
				'postal_code_regex'    => '',
				'languages'            => 'ar,fr-KM',
				'neighbours'           => '',
				'equivalent_fips_code' => '',
                'region-code'=>'002',
                'sub-region-code'=>'014',
                'eea'=>false,
				'flag'     => null,
				'status'               => '1',


			],
            [
				'iso_code_2'                 => 'YT',
				'iso_code_3'                 => 'MYT',
				'iso_numeric'          => '175',
				'fips'                 => 'MF',
				'name'                 =>  'Mayotte',
                'full_name'=>'Departmental Collectivity of Mayotte',
				'capital'              => 'Mamoudzou',
                'citizenship'=>'Mahorais',
				'area'                 => '374',
				'population'           => '159042',
				'continent_code'       => 'AF',
				'tld'                  => '.yt',
                'currency'=>'euro',
                'currency_code'=>'EUR',
                'currency_sub_unit'=>'cent',
				'currency_symbol'=>'\u20ac',
				'calling_code'                => '262',
				'postal_code_format'   => '#####',
				'postal_code_regex'    => '^(d{5})$',
				'languages'            => 'fr-YT',
				'neighbours'           => '',
				'equivalent_fips_code' => '',
                'region-code'=>'002',
                'sub-region-code'=>'014',
                'eea'=>false,
				'flag'     => 'YT.png',


				'status'               => '1',


			],
            [
				'iso_code_2'                 => 'CG',
				'iso_code_3'                 => 'COG',
				'iso_numeric'          => '178',
				'fips'                 => 'CF',
				'name'                 =>  'Congo',
                'full_name'=>'Republic of the Congo',
				'capital'              => 'Brazzaville',
                'citizenship'=>'Congolese',
				'area'                 => '342000',
				'population'           => '3039126',
				'continent_code'       => 'AF',
				'tld'                  => '.cg',
                'currency'=>'CFA franc (BEAC)',
                'currency_code'=>'XAF',
                'currency_sub_unit'=>'centime',
				'currency_symbol'=>'FCF',
				'calling_code'                => '242',
				'postal_code_format'   => '',
				'postal_code_regex'    => '',
				'languages'            => 'fr-CG,kg,ln-CG',
				'neighbours'           => 'CF,GA,CD,CM,AO',
				'equivalent_fips_code' => '',
                'region-code'=>'002',
                'sub-region-code'=>'017',
                'eea'=>false,
				'flag'     => 'CG.png',


				'status'               => '1',


			],
            [
				'iso_code_2'                 => 'CD',
				'iso_code_3'                 => 'COD',
				'iso_numeric'          => '180',
				'fips'                 => 'CG',
				'name'                 =>  'Democratic Republic of the Congo',
                'full_name'=>'Democratic Republic of the Congo',
				'capital'              => 'Kinshasa',
                'citizenship'=>'Congolese',
				'area'                 => '2345410',
				'population'           => '70916439',
				'continent_code'       => 'AF',
				'tld'                  => '.cd',
                'currency'=>'Congolese franc',
                'currency_code'=>'CDF',
                'currency_sub_unit'=>'centime',
				'currency_symbol'=>'CDF',
				'calling_code'                => '243',
				'postal_code_format'   => '',
				'postal_code_regex'    => '',
				'languages'            => 'fr-CD,ln,kg',
				'neighbours'           => 'TZ,CF,SS,RW,ZM,BI,UG,CG,AO',
				'equivalent_fips_code' => '',
                'region-code'=>'002',
                'sub-region-code'=>'017',
                'eea'=>false,
				'flag'     => 'CD.png',


				'status'               => '1',


			],
            [
				'iso_code_2'                 => 'CK',
				'iso_code_3'                 => 'COK',
				'iso_numeric'          => '184',
				'fips'                 => 'CW',
				'name'                 =>  'Cook Islands',
                'full_name'=>'Cook Islands',
				'capital'              => 'Avarua',
                'citizenship'=>'Cook Islander',
				'area'                 => '240',
				'population'           => '21388',
				'continent_code'       => 'OC',
				'tld'                  => '.ck',
                'currency'=>'New Zealand dollar',
                'currency_code'=>'NZD',
                'currency_sub_unit'=>'cent',
                'currency_symbol'=>'$',
				'calling_code'                => '682',
				'postal_code_format'   => '',
				'postal_code_regex'    => '',
				'languages'            => 'en-CK,mi',
				'neighbours'           => '',
				'equivalent_fips_code' => '',
                'region-code'=>'009',
                'sub-region-code'=>'061',
                'eea'=>false,
				'flag'     => 'CK.png',


				'status'               => '1',


			],
            [
				'iso_code_2'                 => 'CR',
				'iso_code_3'                 => 'CRI',
				'iso_numeric'          => '188',
				'fips'                 => 'CS',
				'name'                 =>  'Costa Rica',
                'full_name'=>'Republic of Costa Rica',
				'capital'              => 'San Jose',
                'citizenship'=>'Costa Rican',
				'area'                 => '51100',
				'population'           => '4516220',
				'continent_code'       => 'NA',
				'tld'                  => '.cr',
                'currency'=>'Costa Rican col\u00f3n (pl. colones)',
                'currency_code'=>'CRC',
                'currency_sub_unit'=>'c\u00e9ntimo',
                'currency_symbol'=>'\u20a1',
				'calling_code'                => '506',
				'postal_code_format'   => '####',
				'postal_code_regex'    => '^(d{4})$',
				'languages'            => 'es-CR,en',
				'neighbours'           => 'PA,NI',
				'equivalent_fips_code' => '',
                'region-code'=>'019',
                'sub-region-code'=>'013',
                'eea'=>false,
				'flag'     => 'CR.png',
				'status'               => '1',


			],
            [
				'iso_code_2'                 => 'HR',
				'iso_code_3'                 => 'HRV',
				'iso_numeric'          => '191',
				'fips'                 => 'HR',
				'name'                 =>  'Croatia',
                'full_name'=>'Republic of Croatia',
				'capital'              => 'Zagreb',
                'citizenship'=>'Croatian',
				'area'                 => '56542',
				'population'           => '4491000',
				'continent_code'       => 'EU',
				'tld'                  => '.hr',
                'currency'=>'kuna (inv.)',
                'currency_code'=>'HRK',
                'currency_sub_unit'=>'lipa (inv.)',
				'currency_symbol'=>'kn',
				'calling_code'                => '385',
				'postal_code_format'   => '#####',
				'postal_code_regex'    => '^(?:HR)*(d{5})$',
				'languages'            => 'hr-HR,sr',
				'neighbours'           => 'HU,SI,BA,ME,RS',
				'equivalent_fips_code' => '',
                'region-code'=>'150',
                'sub-region-code'=>'039',
                'eea'=>true,
				'flag'     => 'HR.png',


				'status'               => '1',


			],
            [
				'iso_code_2'                 => 'CU',
				'iso_code_3'                 => 'CUB',
				'iso_numeric'          => '192',
				'fips'                 => 'CU',
				'name'                 =>  'Cuba',
                'full_name'=>'Republic of Cuba',
				'capital'              => 'Havana',
                'citizenship'=>'Cuban',
				'area'                 => '110860',
				'population'           => '11423000',
				'continent_code'       => 'NA',
				'tld'                  => '.cu',
                'currency'=>'Cuban peso',
                'currency_code'=>'CUP',
                'currency_sub_unit'=>'centavo',
                'currency_symbol'=>'\u20b1',
				'calling_code'                => '53',
				'postal_code_format'   => 'CP #####',
				'postal_code_regex'    => '^(?:CP)*(d{5})$',
				'languages'            => 'es-CU',
				'neighbours'           => 'US',
				'equivalent_fips_code' => '',
                'region-code'=>'019',
                'sub-region-code'=>'029',
                'eea'=>false,
				'flag'     => 'CU,png',


				'status'               => '1',


			],
            [
				'iso_code_2'                 => 'CY',
				'iso_code_3'                 => 'CYP',
				'iso_numeric'          => '196',
				'fips'                 => 'CY',
				'name'                 =>  'Cyprus',
                'full_name'=>'Republic of Cyprus',
				'capital'              => 'Nicosia',
                'citizenship'=>'Cypriot',
				'area'                 => '9250',
				'population'           => '1102677',
				'continent_code'       => 'EU',
				'tld'                  => '.cy',
                'currency'=>'euro',
                'currency_code'=>'EUR',
                'currency_sub_unit'=>'cent',
				'currency_symbol'=>'CYP',
				'calling_code'                => '357',
				'postal_code_format'   => '####',
				'postal_code_regex'    => '^(d{4})$',
				'languages'            => 'el-CY,tr-CY,en',
				'neighbours'           => '',
				'equivalent_fips_code' => '',
                'region-code'=>'142',
                'sub-region-code'=>'145',
                'eea'=>true,
				'flag'     => 'true',


				'status'               => '1',


			],
            [
				'iso_code_2'                 => 'CZ',
				'iso_code_3'                 => 'CZE',
				'iso_numeric'          => '203',
				'fips'                 => 'EZ',
				'name'                 =>  'Czech Republic',
                'full_name'=>'Czech Republic',
				'capital'              => 'Prague',
                'citizenship'=>'Czech',
				'area'                 => '78866',
				'population'           => '10476000',
				'continent_code'       => 'EU',
				'tld'                  => '.cz',
                'currency'=>'Czech koruna (pl. koruny)',
                'currency_code'=>'CZK',
                'currency_sub_unit'=>'hal\u00e9r',
				'currency_symbol'=>'K\u010d',
				'calling_code'                => '420',
				'postal_code_format'   => '### ##',
				'postal_code_regex'    => '^(d{5})$',
				'languages'            => 'cs,sk',
				'neighbours'           => 'PL,DE,SK,AT',
				'equivalent_fips_code' => '',
                'region-code'=>'150',
                'sub-region-code'=>'151',
                'eea'=>true,
				'flag'     => 'CZ.png',


				'status'               => '1',


			],
            [
				'iso_code_2'                 => 'BJ',
				'iso_code_3'                 => 'BEN',
				'iso_numeric'          => '204',
				'fips'                 => 'BN',
				'name'                 =>  'Benin',
                'full_name'=>'Republic of Benin',
				'capital'              => 'Porto-Novo',
                'citizenship'=>'Beninese',
				'area'                 => '112620',
				'population'           => '9056010',
				'continent_code'       => 'AF',
				'tld'                  => '.bj',
                'currency'=>'CFA franc (BCEAO)',
                'currency_code'=>'XOF',
                'currency_sub_unit'=>'centime',
				'currency_symbol'=>'XOF',
				'calling_code'                => '+229',
				'postal_code_format'   => '',
				'postal_code_regex'    => '',
				'languages'            => 'fr-BJ',
				'neighbours'           => 'NE,TG,BF,NG',
				'equivalent_fips_code' => '',
                'region-code'=>'002',
                'sub-region-code'=>'011',
                'eea'=>false,
				'flag'     => 'BJ.png',


				'status'               => '1',


			],
            [
				'iso_code_2'                 => 'DK',
				'iso_code_3'                 => 'DNK',
				'iso_numeric'          => '208',
				'fips'                 => 'DA',
				'name'                 =>  'Denmark',
                'full_name'=>'Kingdom of Denmark',
				'capital'              => 'Copenhagen',
                'citizenship'=>'Danish',
				'area'                 => '43094',
				'population'           => '5484000',
				'continent_code'       => 'EU',
				'tld'                  => '.dk',
                'currency'=>'Danish krone',
                'currency_code'=>'DKK',
                'currency_sub_unit'=>'\u00f8re (inv.)',
				'currency_symbol'=>'kr',
				'calling_code'                => '45',
				'postal_code_format'   => '####',
				'postal_code_regex'    => '^(d{4})$',
				'languages'            => 'da-DK,en,fo,de-DK',
				'neighbours'           => 'DE',
				'equivalent_fips_code' => '',
                'region-code'=>'150',
                'sub-region-code'=>'154',
                'eea'=>true,
				'flag'     => 'DK.png',


				'status'               => '1',


			],
            [
				'iso_code_2'                 => 'DM',
				'iso_code_3'                 => 'DMA',
				'iso_numeric'          => '212',
				'fips'                 => 'DO',
				'name'                 =>  'Dominica',
                'full_name'=>'Commonwealth of Dominica',
				'capital'              => 'Roseau',
                'citizenship'=>'Dominican',
				'area'                 => '754',
				'population'           => '72813',
				'continent_code'       => 'NA',
				'tld'                  => '.dm',
                'currency'=>'East Caribbean dollar',
                'currency_code'=>'XCD',
                'currency_sub_unit'=>'cent',
				'currency_symbol'=>'$',
				'calling_code'                => '+1-767',
				'postal_code_format'   => '',
				'postal_code_regex'    => '',
				'languages'            => 'en-DM',
				'neighbours'           => '',
				'equivalent_fips_code' => '',
                'region-code'=>'019',
                'sub-region-code'=>'029',
                'eea'=>false,
				'flag'     => 'DM.png',


				'status'               => '1',


			],
            [
				'iso_code_2'                 => 'DO',
				'iso_code_3'                 => 'DOM',
				'iso_numeric'          => '214',
				'fips'                 => 'DR',
				'name'                 =>  'Dominican Republic',
                'full_name'=>'Dominican Republic',
				'capital'              => 'Santo Domingo',
                'citizenship'=>'Dominican',
				'area'                 => '48730',
				'population'           => '9823821',
				'continent_code'       => 'NA',
				'tld'                  => '.do',
                'currency'=>'Dominican peso',
                'currency_code'=>'DOP',
                'currency_sub_unit'=>'centavo',
				'currency_symbol'=>'RD$',
				'calling_code'                => '+809/829/849',
				'postal_code_format'   => '#####',
				'postal_code_regex'    => '^(d{5})$',
				'languages'            => 'es-DO',
				'neighbours'           => 'HT',
				'equivalent_fips_code' => '',
                'region-code'=>'019',
                'sub-region-code'=>'029',
                'eea'=>false,
				'flag'     => 'DO.png',


				'status'               => '1',


			],
            [
				'iso_code_2'                 => 'EC',
				'iso_code_3'                 => 'ECU',
				'iso_numeric'          => '218',
				'fips'                 => 'EC',
				'name'                 =>  'Ecuador',
                'full_name'=>'Republic of Ecuador',
				'capital'              => 'Quito',
                'citizenship'=>'Ecuadorian',
				'area'                 => '283560',
				'population'           => '14790608',
				'continent_code'       => 'SA',
				'tld'                  => '.ec',
                'currency'=>'US dollar',
                'currency_code'=>'USD',
                'currency_sub_unit'=>'cent',
				'currency_symbol'=>'$',
				'calling_code'                => '593',
				'postal_code_format'   => '@####@',
				'postal_code_regex'    => '^([a-zA-Z]d{4}[a-zA-Z])$',
				'languages'            => 'es-EC',
				'neighbours'           => 'PE,CO',
				'equivalent_fips_code' => '',
                'region-code'=>'019',
                'sub-region-code'=>'005',
                'eea'=>false,
				'flag'     => 'EC.png',


				'status'               => '1',


			],
            [
				'iso_code_2'                 => 'SV',
				'iso_code_3'                 => 'SLV',
				'iso_numeric'          => '222',
				'fips'                 => 'ES',
				'name'                 =>  'El Salvador',
                'full_name'=>'Republic of El Salvador',
				'capital'              => 'San Salvador',
                'citizenship'=>'Salvadoran',
				'area'                 => '21040',
				'population'           => '6052064',
				'continent_code'       => 'NA',
				'tld'                  => '.sv',
                'currency'=>'Salvadorian col\u00f3n (pl. colones)',
                'currency_code'=>'SVC',
                'currency_sub_unit'=>'centavo',
				'currency_symbol'=>'$',
				'calling_code'                => '503',
				'postal_code_format'   => 'CP ####',
				'postal_code_regex'    => '^(?:CP)*(d{4})$',
				'languages'            => 'es-SV',
				'neighbours'           => 'GT,HN',
				'equivalent_fips_code' => '',
                'region-code'=>'019',
                'sub-region-code'=>'013',
                'eea'=>false,
				'flag'     => 'SV.png',


				'status'               => '1',


			],
            [
				'iso_code_2'                 => 'GQ',
				'iso_code_3'                 => 'GNQ',
				'iso_numeric'          => '226',
				'fips'                 => 'EK',
				'name'                 =>  'Equatorial Guinea',
                
				'capital'              => 'Malabo',
				'area'                 => '28051',
				'population'           => '1014999',
				'continent_code'       => 'AF',
				'tld'                  => '.gq',
				'currency_code'        => 'XAF',
				'calling_code'                => '240',
				'postal_code_format'   => '',
				'postal_code_regex'    => '',
				'languages'            => 'es-GQ,fr',
				'neighbours'           => 'GA,CM',
				'equivalent_fips_code' => '',
				'flag'     => '.png',


				'status'               => '1',


			],

        ];


    }
}
